name: Run lighthouse CI When Push
on:
  pull_request:
    branches:
      - main
      - develop
    paths: "frontend/**" #frontend 폴더의 파일이 하나라도 수정됬을 때 trigger
jobs:
  label-check:
    runs-on: ubuntu-latest
    steps:
      - name: PR Label 확인
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: frontend Label 체크
        id: frontend
        if: contains(steps.pr-labels.outputs.labels, ' frontend ')
        run: echo "::set-output name=status::true"

  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 17.4.0
        uses: actions/setup-node@v3
        with:
          node-version: 17.4.0

      - name: Install packages and Build
        run: |
          npm install
          npm run build
        working-directory: ${{ env.working-directory }}

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli
          lhci autorun || echo "Fail to Run Lighthouse CI!"
        working-directory: ${{ env.working-directory }}

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync("./frontend/lhci_reports/manifest.json"));
            let comments = "";

            results.forEach((result) => {
              const { summary, jsonPath } = result;
              const details = JSON.parse(fs.readFileSync(jsonPath));
              const { audits } = details;
              
              const formatResult = (res) => Math.round(res * 100);
              Object.keys(summary).forEach(
                (key) => (summary[key] = formatResult(summary[key]))
              );
              const score = (res) => (res >= 90 ? "🟢" : res >= 50 ? "🟠" : "🔴");
              const comment = [
                `⚡️ Lighthouse report!`,
                `| Category | Score |`,
                `| --- | --- |`,
                `| ${score(summary.performance)} Performance | ${summary.performance} |`,
              ].join("\n");
              const detail = [
                `| ${score(
                  audits["first-contentful-paint"].score * 100
                )} First Contentful Paint | ${
                  audits["first-contentful-paint"].displayValue
                } |`,
              ].join("\n");
              comments += comment + "\n" + detail + "\n";
            });

            core.setOutput('comments', comments)

      - name: comment PR
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: ${{ steps.format_lighthouse_score.outputs.comments}}
